### ISSUE TITLE
Strange behavior on import file

### ISSUE THREAD

**Issue by fred01** [xbreathoflife/hsqldb-csv-importer#2]
Thank you for a quick fix of #1. Now it works like a charm!
But there is another problem. One of my customers sent me a file (archive with that file attached). I got some errors when trying to import it. Also, my co-worker, Fred, complains to me about losing his work table in the same database.

[to_import.zip](https://github.com/xbreathoflife/hsqldb-csv-importer/files/7148170/to_import.zip)

**Comment by xbreathoflife** [comment]
I have fixed this in 0ced2be880b0040f8f47ac5b28f71ccbc28caf3c
I hope it's safer for Fred now :)

**Comment by fred01** [comment]
Great job! Yep, Fred is absolutely fine now :)
